Feature/id 20/planes socios
Team-S-Devs/tarjetags-landing-page pull request #18
Opened 2024-03-18 20:34 UTC by gabygabylagaby

Planes

2024-03-19 00:24 UTC, CatCoder37 approved these changes

2024-03-19 01:01 UTC, just-fabian requested changes
![image](https://github.com/Team-S-Devs/tarjetags-landing-page/assets/90233884/05a9d8dd-3575-4e04-9cc4-eba1516cb577)
Fix: logs and hidden text

2024-03-19 01:04 UTC, just-fabian requested changes
![image](https://github.com/Team-S-Devs/tarjetags-landing-page/assets/90233884/55e2fc3a-c254-46bb-8533-4f31f4dcb24c)
Update the items per plan, for Free Plan, it would be better that the icon of item "Caducidad en 3 meses" be different, like a red X

2024-03-30 01:35 UTC, closed without merging

2024-03-30 01:35 UTC, gabygabylagaby commented
Todo los errores seran corregidos en la rama fix/planes